# Generated by Django 5.0.1 on 2024-01-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_for_competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('patronymic', models.CharField(default=None, max_length=25, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Удалить')),
                ('post', models.CharField(max_length=100, verbose_name='Занимаемая должность')),
                ('regalia', models.TextField(default=None, verbose_name='Заслуги и регалии')),
                ('organization', models.CharField(max_length=100, verbose_name='Место работы')),
                ('status', models.CharField(choices=[('M', 'главный судья'), ('J', 'судья'), ('S', 'секретарь'), ('O', 'наблюдатель')], default='O', max_length=1, verbose_name='Статус на соревнованиях')),
                ('competitions', models.ManyToManyField(blank=True, default='Нет', to='app_for_competitions.competition')),
            ],
            options={
                'db_table': 'judges',
            },
        ),
    ]
