# Generated by Django 5.0.1 on 2024-05-16 10:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_for_competitions', '0005_alter_competitiontask_name_average_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Отчество')),
                ('post', models.CharField(default='Преподаватель ОД (математика, информатика и ИКТ)', max_length=100, verbose_name='Занимаемая должность')),
                ('regalia', models.TextField(default='Преподаватель высшей категории', verbose_name='Заслуги и регалии')),
                ('organization', models.CharField(default='Оренбургское ПКУ', max_length=100, verbose_name='Место работы')),
                ('status', models.CharField(choices=[('M', 'Главный судья'), ('J', 'Судья'), ('S', 'Секретарь'), ('O', 'Наблюдатель')], default='O', max_length=1, verbose_name='Статус на соревнованиях')),
                ('competitions', models.ManyToManyField(blank=True, default='Нет', to='app_for_competitions.competition')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Судья',
                'verbose_name_plural': 'Судьи',
                'db_table': 'judges',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('organization', models.CharField(default='ФГКОУ "Оренбургское ПКУ"', max_length=100, verbose_name='Образовательное учреждение')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_for_competitions.competition', verbose_name='Соревнования')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'db_table': 'participants',
            },
        ),
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_place', models.IntegerField(verbose_name='Сумма мест')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_for_judges.participant', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Результат конкурса',
                'verbose_name_plural': 'Результаты конкурсов',
                'db_table': 'competition_results',
            },
        ),
        migrations.CreateModel(
            name='ParticipantsTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название команды')),
                ('organization', models.CharField(default='ФГКОУ "Оренбургское ПКУ"', max_length=100, verbose_name='Образовательное учреждение')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_for_competitions.competition', verbose_name='Соревнования')),
            ],
            options={
                'verbose_name': 'Участник - команда',
                'verbose_name_plural': 'Участники - команды',
                'db_table': 'participant_teams',
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_for_judges.participantsteam', verbose_name='Команда'),
        ),
        migrations.CreateModel(
            name='TableTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('intermediate_points_1', models.IntegerField(default=0, verbose_name='Промежуточные баллы - 1')),
                ('intermediate_points_2', models.IntegerField(default=0, verbose_name='Промежуточные баллы - 2')),
                ('intermediate_points_3', models.IntegerField(default=0, verbose_name='Промежуточные баллы - 3')),
                ('intermediate_points_4', models.IntegerField(default=0, verbose_name='Промежуточные баллы - 4')),
                ('points', models.IntegerField(default=0, verbose_name='Сумма баллов')),
                ('correction_score_up', models.IntegerField(default=0, verbose_name='Корректирующий балл, если больше')),
                ('correction_score_down', models.IntegerField(default=0, verbose_name='Корректирующий балл, если меньше')),
                ('intermediate_time_1', models.TimeField(default=datetime.time(0, 0), verbose_name='Промежуточное время - 1, мм:сс')),
                ('intermediate_time_2', models.TimeField(default=datetime.time(0, 0), verbose_name='Промежуточное время - 2, мм:сс')),
                ('average_time', models.TimeField(default=datetime.time(0, 0), verbose_name='Среднее время, мм:сс')),
                ('total_time', models.TimeField(default=datetime.time(0, 0), verbose_name='Время, мм:сс')),
                ('correction_time', models.TimeField(default=datetime.time(0, 0), verbose_name='Корректирующее время, мм:сс')),
                ('result_place', models.IntegerField(default=0, verbose_name='Место')),
                ('competition_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_for_competitions.competitiontask', verbose_name='Этап')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_for_judges.participant', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Таблица этапа',
                'verbose_name_plural': 'Таблицы этапов',
                'db_table': 'table_tasks',
            },
        ),
    ]
