# Generated by Django 5.0.1 on 2024-02-01 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_for_competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Отчество')),
                ('post', models.CharField(default='Преподаватель ОД (математика, информатика и ИКТ', max_length=100, verbose_name='Занимаемая должность')),
                ('regalia', models.TextField(default='Преподаватель высшей категории', verbose_name='Заслуги и регалии')),
                ('organization', models.CharField(default='Оренбургское ПКУ', max_length=100, verbose_name='Место работы')),
                ('status', models.CharField(choices=[('M', 'главный судья'), ('J', 'судья'), ('S', 'секретарь'), ('O', 'наблюдатель')], default='O', max_length=1, verbose_name='Статус на соревнованиях')),
                ('competitions', models.ManyToManyField(blank=True, default='Нет', to='app_for_competitions.competition')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Судьи',
                'db_table': 'judges',
            },
        ),
    ]
