# Generated by Django 5.0.1 on 2024-05-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_for_judges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabletask',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
