# Generated by Django 5.0.1 on 2024-02-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_for_judges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='status',
            field=models.CharField(choices=[('M', 'Главный судья'), ('J', 'Судья'), ('S', 'Секретарь'), ('O', 'Наблюдатель')], default='O', max_length=1, verbose_name='Статус на соревнованиях'),
        ),
    ]
