# Generated by Django 5.0.1 on 2024-05-16 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_for_judges', '0002_alter_tabletask_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabletask',
            name='name',
        ),
    ]
