# Generated by Django 5.0.1 on 2024-02-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_for_judges', '0003_participantsteam_alter_judge_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='participantsteam',
            table='participant_teams',
        ),
    ]
