# Generated by Django 5.0.1 on 2024-02-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_for_judges', '0007_alter_tabletask_competition_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletask',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Баллы'),
        ),
    ]
