# Generated by Django 5.0.1 on 2024-05-15 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_for_judges', '0009_competitionresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabletask',
            name='time',
        ),
        migrations.AddField(
            model_name='tabletask',
            name='average_time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Среднее время, мм:сс'),
        ),
        migrations.AddField(
            model_name='tabletask',
            name='correction_score_down',
            field=models.IntegerField(default=0, verbose_name='Корректирующий балл, если меньше'),
        ),
        migrations.AddField(
            model_name='tabletask',
            name='correction_score_up',
            field=models.IntegerField(default=0, verbose_name='Корректирующий балл, если больше'),
        ),
        migrations.AddField(
            model_name='tabletask',
            name='correction_time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Корректирующее время, мм:сс'),
        ),
        migrations.AddField(
            model_name='tabletask',
            name='intermediate_points_1',
            field=models.IntegerField(default=0, verbose_name='Промежуточные баллы - 1'),
        ),
        migrations.AddField(
            model_name='tabletask',
            name='intermediate_points_2',
            field=models.IntegerField(default=0, verbose_name='Промежуточные баллы - 2'),
        ),
        migrations.AddField(
            model_name='tabletask',
            name='intermediate_points_3',
            field=models.IntegerField(default=0, verbose_name='Промежуточные баллы - 3'),
        ),
        migrations.AddField(
            model_name='tabletask',
            name='intermediate_points_4',
            field=models.IntegerField(default=0, verbose_name='Промежуточные баллы - 4'),
        ),
        migrations.AddField(
            model_name='tabletask',
            name='intermediate_time_1',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Промежуточное время - 1, мм:сс'),
        ),
        migrations.AddField(
            model_name='tabletask',
            name='intermediate_time_2',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Промежуточное время - 2, мм:сс'),
        ),
        migrations.AddField(
            model_name='tabletask',
            name='total_time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Среднее время, мм:сс'),
        ),
        migrations.AlterField(
            model_name='competitionresult',
            name='final_place',
            field=models.IntegerField(verbose_name='Сумма мест'),
        ),
        migrations.AlterField(
            model_name='tabletask',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Сумма баллов'),
        ),
    ]
