# Generated by Django 5.0.1 on 2024-05-15 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_for_judges', '0010_remove_tabletask_time_tabletask_average_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabletask',
            name='total_time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Время, мм:сс'),
        ),
    ]
