# Generated by Django 5.0.1 on 2024-01-24 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Сокращенное название')),
                ('fullname', models.CharField(default=None, max_length=200, verbose_name='Полное наименование конкурса')),
                ('date', models.DateField(help_text='Дата начала соревнований', verbose_name='Дата проведения')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'db_table': 'competitions',
            },
        ),
        migrations.CreateModel(
            name='CompetitionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_for_competitions.competition')),
            ],
            options={
                'db_table': 'competition_tasks',
            },
        ),
    ]
