# Generated by Django 5.0.1 on 2024-02-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_for_competitions', '0003_alter_competition_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiontask',
            name='judging',
            field=models.BooleanField(default=True),
        ),
    ]
