# Generated by Django 5.0.1 on 2024-05-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_for_competitions', '0005_alter_competitiontask_name_average_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitiontask',
            name='name_average_time',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='Среднее время'),
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='name_correction_score_down',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='Корректирующий балл, если меньше'),
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='name_correction_score_up',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='Корректирующий балл, если больше'),
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='name_correction_time',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='Корректирующее время'),
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='name_intermediate_points_1',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='Промежуточные баллы - 1'),
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='name_intermediate_points_2',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='Промежуточные баллы - 2'),
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='name_intermediate_points_3',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='Промежуточные баллы - 3'),
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='name_intermediate_points_4',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='Промежуточные баллы - 4'),
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='name_intermediate_time_1',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='Промежуточное время - 1'),
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='name_intermediate_time_2',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='Промежуточное время - 2'),
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='name_points',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='Сумма баллов'),
        ),
        migrations.AlterField(
            model_name='competitiontask',
            name='name_total_time',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='Время'),
        ),
    ]
